### ISSUE TITLE
ubuntu opencv c++版本可行驶区域以及车道线检测效果很差

### ISSUE THREAD

**Issue by zsdfaker** [hpc203/yolopv2-opencv-onnxrun-cpp-py#5]
ubuntu opencv c++版本，条件阈值后识别是ok的，但可行驶区域以及车道线检测效果很差
confThreshold = 0.65
nmsThreshold = 0.55
![Screenshot 2023-02-15 12:00:26](https://user-images.githubusercontent.com/40298406/218951768-f7e1774c-9277-48e2-a7f7-b80952cc8a7e.png)
![Screenshot 2023-02-15 12:01:46](https://user-images.githubusercontent.com/40298406/218951783-68e85edd-1351-4d15-9261-f2789f268ab9.png)

**Comment by hpc203** [comment]
模型是在bdd100k数据集训练出来的，你这个图片是bdd100k数据集里的吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 下午2:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hpc203/yolopv2-opencv-onnxrun-cpp-py] ubuntu opencv c++版本可行驶区域以及车道线检测效果很差 (Issue #5)




 
ubuntu opencv c++版本，条件阈值后识别是ok的，但可行驶区域以及车道线检测效果很差
 confThreshold = 0.65
 nmsThreshold = 0.55

**Comment by zsdfaker** [comment]
> 模型是在bdd100k数据集训练出来的，你这个图片是bdd100k数据集里的吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月15日(周三) 下午2:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [hpc203/yolopv2-opencv-onnxrun-cpp-py] ubuntu opencv c++版本可行驶区域以及车道线检测效果很差 (Issue #5) ubuntu opencv c++版本，条件阈值后识别是ok的，但可行驶区域以及车道线检测效果很差 confThreshold = 0.65 nmsThreshold = 0.55 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是的，而且这个就是项目opencv分支对应的images目录下的图片

**Comment by zsdfaker** [comment]
解决了，output的索引值与代码中不太一致
float* pdrive_area = (float*)outs[4].data;
float* plane_line = (float*)outs[0].data;
